** Swear an Iron Vow

When you swear upon iron to complete a quest, write your vow and give the quest a rank. Then, roll +heart. If you make this vow to a person or community with whom you share a bond, add +1.

On a *strong hit*, you are emboldened and it is clear what you must do next ([[file:../fate/ask-the-oracle.org][Ask the Oracle]] if unsure). Take +2 momentum.

On a *weak hit*, you are determined but begin your quest with more questions than answers. Take +1 momentum, and envision what you do to find a path forward.

On a *miss*, you face a significant obstacle before you can begin your quest. Envision what stands in your way ([[file:../fate/ask-the-oracle.org][Ask the Oracle]] if unsure), and choose one.
  - You press on: Suffer -2 momentum, and do what you must to overcome this obstacle.
  - You give up: [[file:forsake-your-vow.org][Forsake Your Vow]].

*** Details
:PROPERTIES:
:move-stats: track|heart
:VISIBILITY: folded
:END:

When you encounter a wrong that must be made right, seek to fulfill a personal ambition, or give your word to serve someone, make this move.

Fictionally, an iron vow is ceremonial. You touch a piece of iron and speak your vow. Don’t just make the move. Envision how your character enacts the ceremony. What do you do? What do you say? Is this a moment of grudging acceptance or one of fiery determination?

Set the rank of your quest based on what you know of the challenges you will face, or [[file:../fate/ask-the-oracle.org][Ask the Oracle]]. Higher ranked quests require more effort (both in your narrative and through session-time and focus), but offer greater experience rewards. An epic quest could be the endeavor of a lifetime, while a troublesome quest might be resolved in a few scenes.

It is not necessary to resolve one vow before swearing another. In fact, the intent of these rules is for your character to run afoul of new situations and get side-tracked with new vows even while attempting to complete a separate quest. This is the life of the Ironsworn.

Based on the results of this move, your path may be clear (a *strong hit*), or more investigation may be required to identify your next steps (a *weak hit*).

On a *miss*, you face a serious obstacle at the very start which prevents you from undertaking this quest. It might be a sudden event, someone working against you or refusing your aid, or a personal conviction which must be overcome. When in doubt about what happens, [[file:../fate/ask-the-oracle.org][Ask the Oracle]]. It should be significant and not easily dealt with. Also, when you resolve this obstacle, you won’t [[file:reach-a-milestone.org][Reach a Milestone]] for your quest. You aren’t actually able to make progress on the vow until you overcome this initial challenge.

You also have the option, on a *miss*, to come to the realization that your vow was made impulsively or without support, and you may simply give up. If you do, [[file:forsake-your-vow.org][Forsake Your Vow]].

When allies join together to *Swear an Iron Vow*, one of you speaks for the group and makes the move. The others can commit to the cause with the [[file:../relationship/aid-your-ally.org][Aid Your Ally]] move. If you score a hit and take +momentum, or score a *miss* and choose to suffer -momentum, only the character making the move adjusts their momentum track. Once your quest is underway, you share a progress track and mark progress together.

#+STARTUP: showall
# Local Variables:
# eval: (flycheck-mode -1)
# End:
