** Endure Stress
When you face mental shock or despair, suffer -spirit equal to your foe’s rank or as appropriate to the situation. If your spirit is 0, suffer -momentum equal to any remaining -spirit.

Then, roll +heart or +spirit, whichever is higher.

On a *strong hit*, choose one.
  - Shake it off: If your spirit is greater than 0, suffer -1 momentum in exchange for +1 spirit
  - Embrace the darkness: Take +1 momentum

On a *weak hit*, you press on.

On a *miss*, also suffer -1 momentum. If you are at 0 spirit, you must mark shaken or corrupted (if currently unmarked) or roll on the following table:

|  Roll | Result                                  |
|-------+-----------------------------------------|
|  1-10 | You are overwhelmed.¹                   |
| 11-25 | You give up.²                           |
| 26-50 | You give in to a fear or compulsion.³   |
| 51-00 | You persevere.                          |

¹ [[file:face-desolation.org][Face Desolation]]

² [[file:../quest/forsake-your-vow.org][Forsake Your Vow]]

³ You act against your better instincts.

*** Details
:PROPERTIES:
:move-stats: > heart spirit
:VISIBILITY: folded
:END:

Make this move when your courage fails you, when you are unnerved or disheartened, or when you act against your best intentions.

When you are forced to [[file:../fate/pay-the-price.org][Pay the Price]], you should *Endure Stress* if mental hardship is an obvious and dramatic outcome of the current situation. Also, some moves and assets will direct you to Endure Stress as a cost or concession, and may indicate a specific amount of stress to suffer.

If you are demoralized or frightened by an NPC foe, you can use their rank to determine amount of stress you must suffer. If the amount of stress is not provided or obvious, use the following guidelines.

  - Troublesome (1 stress) :: An unsettling incident or a frustrating failure.
  - Dangerous (2 stress) :: A distressing incident or an upsetting failure.
  - Formidable (3 stress) :: A horrifying incident or a demoralizing failure.
  - Extreme (4 stress) :: A heart-rending incident or traumatic failure.
  - Epic (5 stress) :: A soul-shattering incident or the loss of all hope.

If in doubt, make it dangerous (2 stress).

Next, reduce your spirit track by the amount suffered. If your spirit is at 0, apply any remaining -spirit to your momentum track. Then, roll.

On a *strong hit*, you are unfazed. You can suffer 1 less spirit or take +1 momentum. On a *weak hit*, you are rattled but carry on.

As with the [[file:endure-harm.org][Endure Harm]] move, when you score a *miss* you need to make an important decision. Do you risk the potential for desolation by rolling on the oracle table, or mark a debility? The shaken debility is temporary and can be dealt with through the [[file:../adventure/heal.org][Heal]] or [[file:../relationship/sojourn.org][Sojourn]] moves, but becoming corrupted is a permanent, life-altering event.

If you’ve scored a *miss* and your debilities are both marked, you must roll on the table to determine your fate.
#+STARTUP: showall
# Local Variables:
# eval: (flycheck-mode -1)
# End:
