** Out of Supply

When your supply is exhausted (reduced to 0), mark unprepared. If you suffer additional -supply while unprepared, you must exchange each additional -supply for any combination of -health, -spirit or -momentum as appropriate to the circumstances.

*** Details
:PROPERTIES:
:VISIBILITY: folded
:END:

When you and your allies reduce your supply to 0 (through a choice or result of another move), you each mark unprepared. The unprepared debility can be cleared when you score a hit on the [[file:../relationship/sojourn.org][Sojourn]] move and choose the equip option.

While you are unprepared, you cannot increase your supply track. If you suffer additional -supply while unprepared, you and your allies must exchange each -supply for some combination of -momentum, -health, or -spirit. Select an option appropriate to the situation. A lack of provisions can have an obvious impact on your fitness, morale, and readiness for challenges.

#+STARTUP: showall
# Local Variables:
# eval: (writegood-mode -1)
# End:
