** Face Danger

When you attempt something risky or react to an imminent threat, envision your action and roll. If you act...

  - With speed, agility, or precision: Roll +edge.
  - With charm, loyalty, or courage: Roll +heart.
  - With aggressive action, forceful defense, strength, or endurance: Roll +iron.
  - With deception, stealth, or trickery: Roll +shadow.
  - With expertise, insight, or observation: Roll +wits.

On a *strong hit*, you are successful. Take +1 momentum.

On a *weak hit*, you succeed, but face a troublesome cost. Choose one.

  - You are delayed, lose advantage, or face a new danger: Suffer -1 momentum.
  - You are tired or hurt: [[file:../suffer/endure-harm.org][Endure Harm]] (1 harm).
  - You are dispirited or afraid: [[file:../suffer/endure-stress.org][Endure Stress]] (1 stress).
  - You sacrifice resources: Suffer -1 supply.

On a *miss*, you fail, or your progress is undermined by a dramatic and costly turn of events. [[file:../fate/pay-the-price.org][Pay the Price]].

*** Details
:PROPERTIES:
:move-stats: edge heart iron shadow wits
:VISIBILITY: folded
:END:

The Face Danger move is a catch-all for risky, dramatic, or complex actions not covered by another move. If you’re trying to overcome an obstacle or resist a threat, make this move to see what happens. You select which stat to roll based on how you address the challenge.

A *strong hit* means you succeed. You are in control. What do you do next?

A *weak hit* means you overcome the obstacle or avoid the threat, but not without cost. Choose an option and envision what happens next. You don’t have complete control. Consider how the situation might escalate, perhaps forcing you to react with another move.

A miss means you are thwarted in your action, fail to oppose the threat, or make some progress but at great cost. You must [[file:../fate/pay-the-price.org][Pay the Price]].

#+STARTUP: showall
# Local Variables:
# eval: (writegood-mode -1)
# End:
