** Heal

When you treat an injury or ailment, roll +wits. If you are mending your own wounds, roll +wits or +iron, whichever is lower.

On a *strong hit*, your care is helpful. If you (or the ally under your care) have the wounded condition, you may clear it. Then, take or give up to +2 health.

On a *weak hit*, as above, but you must suffer -1 supply or -1 momentum (your choice).

On a *miss*, your aid is ineffective. [[file:../fate/pay-the-price.org][Pay the Price]].

*** Details
:PROPERTIES:
:move-stats: wits iron
:VISIBILITY: folded
:END:

When you tend to physical damage or sickness—for yourself, an ally, or an NPC—make this move. Healing might be represented by staunching bleeding, binding wounds, applying salves, or using herbs to brew a tonic.

Healing takes time. A few minutes for a quick treatment to get someone on their feet. Hours or perhaps days for more severe injuries. Use what seems appropriate to the circumstances, and consider how this downtime affects your quests and other things going on in your world.

A miss can mean you’ve caused harm rather than helping, or some perilous event interrupts your care.

NPCs who are not companions do not have a health track. When you attempt to Heal them, make this move and apply the result through the fiction. They will improve, or not, as appropriate to the move’s outcome.

#+STARTUP: showall
# Local Variables:
# eval: (writegood-mode -1)
# End:
