** Make Camp

When you rest and recover for several hours in the wild, roll +supply.

On a *strong hit*, you and your allies may each choose two. On a *weak hit*, choose one.

  - Recuperate: Take +1 health for you and any companions.
  - Partake: Suffer -1 supply and take +1 health for you and any companions.
  - Relax: Take +1 spirit.
  - Focus: Take +1 momentum.
  - Prepare: When you break camp, add +1 if you [[file:undertake-a-journey.org][Undertake a Journey]].

On a *miss*, you take no comfort. [[file:../fate/pay-the-price.org][Pay the Price]].

*** Details
:PROPERTIES:
:move-stats: supply
:VISIBILITY: folded
:END:

Making camp can be a purely narrative activity and can be abstracted or roleplayed as you like. However, if you need to recover from the struggle of your adventures while traveling through the wilds, make this move.

Unlike most moves, you will not roll + a stat. Instead, you roll +supply. This represents your access to provisions and gear. Huddling in your cloak on the cold ground is a different experience than a warm fire, good food, and a dry tent.

On a *strong hit*, choose two from the list. You may not select a single option more than once. On a *weak hit*, choose one. If you recuperate or partake, you can also apply those benefits to your companions (NPC assets).

If you are traveling with allies, only one of you makes this roll for the group. Each of you may then choose your own benefits on a strong or *weak hit*.

On a *miss*, you gain no benefits of your downtime. Perhaps you suffered troubling dreams ([[file:../suffer/endure-stress.org][Endure Stress]]). Poor weather may have left you weary and cold ([[file:../suffer/endure-harm.org][Endure Harm]]). Or, you were attacked. If in doubt, roll on the [[file:../fate/pay-the-price.org][Pay the Price]] table or [[file:../fate/ask-the-oracle.org][Ask the Oracle]] for inspiration. Depending on what you envision, you can play to see what happens, or jump to the next day as you continue on your journey the worse for wear.

#+STARTUP: showall
# Local Variables:
# eval: (writegood-mode -1)
# End:
