** Turn the Tide

Once per fight, when you risk it all, you may steal initiative from your foe to make a move (not a progress move). When you do, add +1 and take +1 momentum on a hit.

If you fail to score a hit on that move, you must suffer a dire outcome. [[file:../fate/pay-the-price.org][Pay the Price]].

*** Details
:PROPERTIES:
:VISIBILITY: folded
:END:

This move represents a last ditch effort to recover control of the fight. It is that moment when all seems lost, but the hero somehow rallies.

*Turn the Tide* lets you take initiative and make a move. The move can be whatever is appropriate under the circumstance—likely [[file:strike.org][Strike]] or [[file:../secure-an-advantage][Secure an Advantage]]. Roll the move (add +1), and act on the results. If you’ve scored a hit, you may take an additional +1 momentum. Then, play to see what happens. Hopefully this bold action is a turning point for the fight.

Here’s the catch: If you score a *miss* when you make your move, you should add extra severity to the consequences. You might face additional harm. Your weapon is broken. Your companion is grievously wounded. Consider the result of your failure and give it teeth. If in doubt, [[file:../fate/ask-the-oracle.org][Ask the Oracle]].

Narratively, this is a dramatic moment. Focus on it. Envision your character’s action. You struggle to your feet and raise your sword, your eyes hardening with determination. You spur your mount into a desperate charge. You grab your opponent’s blade in your bare hand. You pull the dagger from your boot and lunge. Or, perhaps you state your name, lament the killing of your father, and tell your foe to prepare for death.

#+STARTUP: showall
# Local Variables:
# eval: (flycheck-mode -1)
# End:
