** Aid Your Ally

When you [[file:../adventure/secure-an-advantage.org][Secure an Advantage]] *in direct support of an ally*, and score a hit, they (instead of you) can take the benefits of the move. If you are in combat and score a *strong hit*, you and your ally have initiative.

*** Details
:PROPERTIES:
:VISIBILITY: folded
:END:

When you take an action to aid an ally (another player’s character) through the [[file:../adventure/secure-an-advantage.org][Secure an Advantage]] move, you can hand over the benefits of that move to your ally. This represents setting your ally up for success through a supporting action. You might be distracting a foe in combat, scouting ahead on a journey, or giving them encouragement as you stand against a dire threat.

If you score a *strong hit* when you [[file:../adventure/secure-an-advantage.org][Secure an Advantage]], your ally makes the choice between +2 momentum or making an immediate move with a +1 add. If you have an asset which gives you any additional benefits on the outcome of a *Secure an Advantage* move, your ally also takes those benefits (instead of you).

In combat, this is a proactive move, made when you have initiative. If you score a *strong hit*, you and your ally both take or retain initiative.

On a *weak hit* when you [[file:../adventure/secure-an-advantage.org][Secure an Advantage]], your ally takes +1 momentum. But, this advantage is fleeting or your situation becomes more complicated or dangerous. If you are in combat, you both lose initiative.

On a *miss*, one or both of you should [[file:../fate/pay-the-price.org][Pay the Price]] as appropriate to the circumstances and your intent when making the move. If in doubt, [[file:../fate/ask-the-oracle.org][Ask the Oracle]]. As with a *weak hit*, you both lose initiative when in combat.

If multiple characters make this move to contribute to an ally action, all [[file:../adventure/secure-an-advantage.org][Secure an Advantage]] bonuses will stack. As long as someone scores a *strong hit*, the target character can take or retain initiative.

Don’t ping pong this move back and forth between two characters in an attempt to build momentum. Envision what you are doing to *Aid Your Ally*, make the [[file:../adventure/secure-an-advantage.org][Secure an Advantage]] move, resolve it, and hand the reins over to your ally as they leverage the advantage. Keep it moving. Make things happen.

#+STARTUP: showall
# Local Variables:
# eval: (flycheck-mode -1)
# End:
