** Test Your Bond
When your bond is tested through conflict, betrayal, or circumstance, roll +heart.

On a *strong hit*, this test has strengthened your bond. Choose one.
  - Take +1 spirit.
  - Take +2 momentum.

On a *weak hit*, your bond is fragile and you must prove your loyalty. Envision what they ask of you ([[file:../fate/ask-the-oracle.org][Ask the Oracle]] if unsure), and do it (or Swear an Iron Vow). If you decline or fail, clear the bond and [[file:../fate/pay-the-price.org][Pay the Price]].

On a *miss*, or if you have no interest in maintaining this relationship, clear the bond and [[file:../fate/pay-the-price.org][Pay the Price]].

*** Details
:PROPERTIES:
:move-stats: heart
:VISIBILITY:
:END:

Bonds are not necessarily everlasting. Events in your story may cause your bond to be tested. How strong is your commitment? If you seek to maintain this bond, at what cost? When you are forced to act against a community or person you share a bond with, fail in a crucial task for them, or they break faith with you, make this move.

You should *Test Your Bond* within the community or in the company of the person with whom you share the bond. If an incident forces this test, but you aren’t in a position to resolve it, make a note. Then, make this move when you next come in contact. If extended time passes without making the test (days, weeks, or months, depending on the circumstance), clear the bond and be done with it.

If you and your allies share a bond with an NPC or community, and you act together to [[file:test-your-bond.org][Test Your Bond]], only one of you makes this move.

#+STARTUP: showall
# Local Variables:
# eval: (flycheck-mode -1)
# End:
